version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: libman
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run start:dev
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: libman
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres-data:
